name: CICD_workflow

on:
  push:
    branches:
      - main

jobs:
  run-tests: 
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Make
        run: sudo apt install make -y
      - name: Create Environment
        run: make requirements
      - name: Dev Setup
        run: make dev-setup
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Run Tests
        run: make run-checks